import random
from time import time
import time
brains=0
braun=0
stamina=0
evilness=0
power=0
Evil_Laughter=0
inventing=0
speed=0
answer=''
evilPowers=['Good at Laughing Evilly','Super Strength','Telekenisis','Super Speed','Can Make Cool Gadgets','Has 99999 IQ']
evilFirstName=['Green','Scary','Big','Bad','Destroyer','Evil','Crazy','Mad','Emotional','Boom']
evilLastName=['Monkey','Face','Wolf','The Dangerous','McChicken','Damage','Mountain','Bomba','Man','Eater','Chungus','Thanatos']
print("Are you ready to create a super villain with the Super Villain Genereator 3000? (Warning, we can't guarantee your safety)")
print("Enter Y for yes or N for no:")
answer=input()
answer=(answer.upper())
while answer!="Y":
    print("I'm sorry, but you have to enter Y to continue!")
    print("Enter Y for yes or N for no:")
    answer=input()
    answer=(answer.upper())
print("Great, let's get started!")
time.sleep(2)
print("Randomizing name...")
for i in range(3):
    print("...........")
    time.sleep(3)
print("(Grab some popcorn! It may take a while...)")
print("")
time.sleep(2)
evilName=random.choice(evilFirstName)+ " " +random.choice(evilLastName)
print("Your Super Villain Name is:")
print(evilName)
print("")
time.sleep(3)
print("Now it's time to see what evil power you have!")
time.sleep(2.5)
print("(generating super villain power...)")
for i in range(2):
    print("...........")
    time.sleep(3)
print("(almost there...)")
time.sleep(2)
power=random.choice(evilPowers)
print("Your new evil power is:")
time.sleep(2)
print(power)
print("")
time.sleep(3)
print("Last but not least, let's generate your stats!")
time.sleep(2)
print("Will you be Super Smart? Super Strong? Super Good Looking?")
time.sleep(2)
print("Time to find out!")
for i in range(3):
    print("...........")
    time.sleep(3)
    brains=random.randint(1,20)
braun=random.randint(1,20)
stamina=random.randint(1,20)
evilness=random.randint(1,20)
Evil_Laughter=random.randint(1,20)
inventing=random.randint(1,20)
speed=random.randint(1,20)
print("Your new stats are:")
print("")
time.sleep(2)
print("Brains: ", brains)
time.sleep(2)
print("Braun: ", braun)
time.sleep(2)
print("Stamina: ", stamina)
time.sleep(2)
print("Evilness: ", evilness)
time.sleep(2)
print("Evil Laughter: ", Evil_Laughter)
time.sleep(2)
print("Inventing: ", inventing)
time.sleep(2)
print("Speed: ", speed)
print("")
time.sleep(2)
print("Here is a summary of your new Super Villain!")
print("")
time.sleep(2)
print("Character Summary:")
print("")
print("")
time.sleep(2)
print("Super Villain Name: ", evilName)
time.sleep(2)
print("Super Power: ", power)
print("")
time.sleep(2)
print("Brains: ", brains)
time.sleep(2)
print("Braun: ", braun)
time.sleep(2)
print("Stamina: ", stamina)
time.sleep(2)
print("Evilness: ", evilness)
time.sleep(2)
print("Evil Laughter: ", Evil_Laughter)
time.sleep(2)
print("Inventing: ", inventing)
time.sleep(2)
print("Speed: ", speed)
time.sleep(2)
print("Thank you for using the Super Villain Generator 3000!")
time.sleep(2)
print("Tell all your friends!")